services:
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
      args:
        API_URL: https://api.squiddy.me/bridge
    restart: unless-stopped
  backend:
    build: ./backend
    restart: unless-stopped

